env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
rules:
  "comma-dangle": ["error", "never"]
  "no-unused-expressions": 0
  "chai-friendly/no-unused-expressions": 2
  "max-len": ["error", 100]
plugins:
  - "chai-friendly"
